### ISSUE TITLE
Is there an official AWSM Registry planned?

### ISSUE THREAD

**Issue by eahefnawy** [awsm-org/awsm#13]
now that you can publish your modules on npm, maybe we don't need a registry after all?!

**Comment by austencollins** [comment]
There is!  It will focus on search and discovery first.

**Comment by eahefnawy** [comment]
can't we just search for `awsm` on npm?! :D

**Comment by austencollins** [comment]
@eahefnawy Yes, you can do that too :)  But only for aws-modules using the nodejs runtime.  

We have big plans for the future of awsm.  Making our own registry is a small but integral part of those plans.

**Comment by eahefnawy** [comment]
oh yeah. I totally forgot about the other runtimes :)

Can't wait!
