### ISSUE TITLE
Rename awsm.json inside lambda directory

### ISSUE THREAD

**Issue by binoculars** [awsm-org/awsm#17]
This gets very confusing, having an `awsm.json` in the main directory and the lambda subdirectory.

I propose keeping `awsm.json` in the main directory and having either `lambda.json` or `endpoint.json` in the lambda subdirectory.

Example:

```
module
    awsm.json
    package.json
    awsm
        lambda1
            lambda.json
            handler.js
            index.js
            event.json
    lib
        modularcode.js
```

I believe this will eliminate confusion--especially when we as developers usually have many tabs open in our IDEs.

**Comment by eahefnawy** [comment]
+1

I was actually gonna suggest that as well :)

**Comment by doapp-ryanp** [comment]
LOVE it. I am going to work it into the `es6-modular` branch I'm working on tonight. Keep and eye on the [JAWS Roadmap doc](https://docs.google.com/document/d/1SeTgtsQc620vcwgGMZ4F2yuWVf-A3JmpTn1VT8pKYsA/edit) with updates.

**Comment by binoculars** [comment]
Thanks, Ryan!

**Comment by doapp-ryanp** [comment]
no thank you

**Comment by doapp-ryanp** [comment]
just to close the loop, we are going with `lambda.awsm.json` for now. https://github.com/jaws-framework/JAWS/commit/0631f44b2e02347d1d95f678e6adb476bae1773d

**Comment by binoculars** [comment]
:+1:
